name: Update Unsupported Characters

on:
  workflow_dispatch:
  push:
    paths:
      - 'public/fonts/kiwi-maru-unsupported-chars.txt'

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    - name: Commit changes
      run: |
        git add public/fonts/kiwi-maru-unsupported-chars.txt
        git diff --quiet && git diff --staged --quiet || \
        git commit -m "chore: update unsupported characters"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main

    - name: Deploy to Vercel
      run: |
        echo "VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}" >> .env
        echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }}" >> .env
        vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm
